import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

export interface FetchRpcDeclarationBuilder {
  path: string
  method: string
}

export function writeFetchRpcDeclaration(
  builder: FetchRpcDeclarationBuilder[],
  path: string,
) {
  writeFileSync(
    `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unconfigurator
export {};
declare global {
${`  ${builder
  .map(
    _ =>
      `function fetch(input: '${join(
        '/_unconfigurator',
        _.path,
      )}', init?: Omit<RequestInit, 'method'> & { method: '${
        _.method
      }' }): Promise<Response>;`,
  )
  .join('\n  ')}`}
}
  `,
    path,
  )
}
